version: '3'
services:
  flask:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  nextjs:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    env_file:
      - .env
